### ISSUE TITLE
How it is different from using Autoprefixer with add:false option?

### ISSUE THREAD

**Issue by jitendravyas** [johnotander/postcss-remove-prefixes#5]

**Comment by johno** [comment]
Good question!

The `add: false` option on autoprefixer only removes outdated vendor prefixes. This library removes _all_ prefixes. This library is useful for when you inherit code that contains lots of vendor prefixes in source since you can then strip all prefixes and then pipe the source through autoprefixer as part of a new build process. After all, no one wants to look at vendor prefixes in their source code : )

**Comment by jitendravyas** [comment]
Thanks for the reply. Now I wonder what is the difference between outdated vendor prefixes and all prefixes.

**Comment by johno** [comment]
An outdated vendor prefix would be `-webkit-border-radius`. All browsers have supported `border-radius` for quite a while now so it is no longer necessary. However, many legacy css codebases might still contain them.
